### ISSUE TITLE
Need Text and RPC updates regarding tenant support

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#14]
We have no text for the YANG model regarding this.

We also have no updates in YANG/text for how this is supported over RPC.

**Comment by matsusato3** [comment]
Now working on it

**Comment by lbertz02** [comment]
Per discussion we assume a client id is associated with a tenant id.
In this case I would suggest a small section for multi-tenant agents where we add the client_id to the FPC-Topology.

In an appendix I would offer a simplistic example RPC that allows the allocation of a Client ID from the agent for a given tenant ID.  I would NOT make this standard as it requires too many security considerations that are outside of the scope of this document.

**Comment by lbertz02** [comment]
Noted in implementation status.
