### ISSUE TITLE
Need to decide if we should add Direction to ietf-dmm-fpcbase.yang's fpc-rule:descriptor

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#2]
The current design (Google docs) has a direction value on the Descriptor in the Rule.   I've been a big advocate of Direction but over time, I think that it may no longer be necessary IF we make consistent the direction for tft terminology, RFC 6088 and Direction in RFC 5777 / Filter Rule.   

If a reconciliation between terms can be made the Direction attribute is not necessary.  This is a tradeoff:
- The FPC Client MUST properly format all Descriptors to the assumed FPC direction
- The Agent / DPN does not need to sort / reformat the Descriptors. 

I believe harmonizing and eliminating the Direction is a small amount of work on the FPC Client and, if it reuses the Descriptor, will ensure that the impact is minimized.   Further, 2 of the 3 elements, Agent and DPN, will not require further processing.

**Comment by matsusato3** [comment]
My intent to Direction in Descriptor is that it's a part of Policy to apply Context so that the direction in the Context, which means UL/DL, should be derived from the policy.

**Comment by lbertz02** [comment]
I am fine with this once the Policy / Context change is merged.

**Comment by lbertz02** [comment]
Closing issue after accepting the Policy/Context change.
