### ISSUE TITLE
Context Directionality should include 'both'

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#23]
Section 4.3.2.2 states

Direction:
    Specifies which side of connection at the DPN indicated, "uplink" or "downlink". 

should change to 

Direction:
    Specifies which side of connection at the DPN indicated, "uplink", "downlink" or "both".

Agent implications:
1. Processing in the DPN must now consider which attributes are tied to uplink as opposed to downlink.  This is easily determined by the role(s) assumed by the DPN or, more often, by the attribute type.
2. This will speed processing.

Text recommendations.  Change language of 4.3.2.2. as described above.  No further text required regarding how attributes are applied is necessary.

YANG recommendations: No change. Directionality and DPN are still a compound key.  Note that you can now get an error by adding the same DPN in all 3 values.  In such a case a specific error could be raised.  Will await feedback on the matter.

**Comment by matsusato3** [comment]
I understand that idea. But the entry of dpns list includes tunnel related attributes which each direction has its own.

**Comment by lbertz02** [comment]
Without a 'both' in the direction attribute the agent must parse ALL entries in order to understand that 'both' is in effect. That means 2x the shallow entries (no data in the ul/dl).  For southbound (Agent => DPN) phases that implies waiting a bit or, in a worst case design, a 2 pass system across the DPNs.

If the presence of both ul/dl is idempotent when compared to only the ul or dl being present then we have no issue.  However, most implementations will not view all transactions this way and it may result in 2x the southbound traffic.

Design options:
OPTION 1: include 'both' in direction.  
OPTION 2: Include an "ordered-by user" in the list and note it is sorted by DPN in the description and text.  This will cluster the ul/dl entries together but require the Client to behave in a non-COTS manner, i.e. stock over the wire libraries for NetConf will not necessarily be compliant.
OPTION 3: Do nothing and take the list search penalty on the Agent.  
OPTION 4: Make ul/dl children of the DPN list and require uniqueness for the DPN list.

Raising other options is appreciated.  

Given these options I vote in the following order:
Option 1, Option 4 but don't like the extra layer of depth, then 3 and want to avoid Option 2 at all costs as it may be more work to override default library sorting than to do something else entirely.

**Comment by lbertz02** [comment]
1. Sorry, pressed wrong button.
2. We are not saying that each direction goes away.  What if we add the following language to the definition - "When the direction is 'both', the associated configuration must be applicable in both directions; otherwise a specific direction of 'ul' or 'dl' MUST be used."

In the case of a simple Context pointing to Ports this is the case (you want the Port to apply to all directions).

**Comment by matsusato3** [comment]
OK, I'll edit the text.
