### ISSUE TITLE
Optional Feature - Policy tree provisioning support in CONF and CONF_BUNDLES

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#28]
It has been requested to support the provisioning of policy entities, e.g. Actions, Descriptors, Policies and Policy-Groups, in the CONF and CONF_BUNDLES messages.  This will permit small, dynamic policies that are required to be reused and provisioned on short SLA over the wire.  It will be an optional feature.

**Comment by matsusato3** [comment]
I'd recommend that Policy structure in Context, not as references to the config datastore.

**Comment by lbertz02** [comment]
This will be added as an if-feature to the RPC.
