### ISSUE TITLE
Need Confirmation that the following are no longer necessary

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#3]
> > Can be captured with the fpc-name, i.e. "vrf:xxx"
> >             case vrf {
> >               leaf vrf {
> >                   type fpcp-vrf-id;
> >               }
> >             }
> > NA specific - is it required as part of spec or should NA operators have this as an extension?
> >             case cipa {
> >               leaf cipa {
> >                   type empty;
> >               }
> >             }

**Comment by matsusato3** [comment]
As I mentioned in the issue-list in the google-doc, I have no idea how the mobility system defined in IETF handles vrf. I think that it's not necessary.

**Comment by lbertz02** [comment]
Thanks for the response.  I have removed all VRF from the YANG. 

CIPA (child protections) flag has been moved out of the YANG and will be implementation specific - it is a small statement / augment for an implemetation add back if they like.  Example YANG is below:
    grouping is-cipa {
       leaf cipa {
        type boolean;
      }
    }
    augment "/fpcagent:fpc-entities/fpcagent:contexts" {
      uses fpc:is-cipa;
    }
    augment "/fpcagent:configure/fpcagent:input/fpcagent:op_body/fpcagent:create_or_update/fpcagent:contexts" {
      uses fpc:is-cipa;
    }
    augment "/fpcagent:configure-bundles/fpcagent:input/fpcagent:bundles/fpcagent:op_body/fpcagent:create_or_update/fpcagent:contexts" {
      uses fpc:is-cipa;
    }
