### ISSUE TITLE
Integration of PMIP and Threegpp as default FPC Options (YANG reduction)

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#30]
By integrating policy extensions, PMIP and Threegpp into fpcbase module a few hundred lines of augments can be eliminated while providing case statements in some of the empty choice statements in fpcbase.  This eliminates > 15 augments.

**Comment by matsusato3** [comment]
Ack

**Comment by lbertz02** [comment]
Per weekly team meeting on 10/27.  No action will be taken and issue will be closed.  Affected projects have agreed to note the YANG deviation and ensure that over the wire and data model syntax/semantics are conformant (as is practical) to the specification.
