### ISSUE TITLE
Eliminate ul/dl children of Contexts and use only DPN list instead

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#31]
It has been proposed to consolidate the multi-DPN and single DPN provisioning styles by the elimination of the ul/dl children under Contexts.  This creates a single, consistent method for provisioning.

**Comment by matsusato3** [comment]
Question: How does an agent store ul/dl specific values, like TEID, GRE-Key things without that children in the Context?

**Comment by lbertz02** [comment]
We use the mobility-tunnel-parameters under the DPN.  Below is a sample
{
    "input": {
        "op-id": "1",
        "contexts": [
            {
                "instructions": {
                    "instr-3gpp-mob": "session uplink downlink"
                },
                "context-id": "/imsi:9135551234/apn:a.example.com",
                "dpn-group": "site1-l3",
                "delegating-ip-prefixes": [
                    "192.168.1.5/32"
                ],
                "dpns": [
                    {
                        "dpn-id": "dpn1",
                        "direction": "uplink",
                        "tunnel-local-address": "192.168.1.1",
                        "tunnel-remote-address": "10.1.1.1",
                        "mobility-tunnel-parameters": {
                            "tunnel-type": "ietf-dmm-threegpp:gtpv1",
                            "tunnel-identifier": "3333"
                        }
                    },
                {
                        "dpn-id": "dpn1",
                        "direction": “downlink”,
                        "tunnel-local-address": "192.168.1.1",
                        "tunnel-remote-address": "10.1.1.1",
                        "mobility-tunnel-parameters": {
                                "tunnel-type": "ietf-dmm-threegpp:gtpv1",
                             "tunnel-identifier": "2222"
                     }
                    }  
                ],
                "imsi": "9135551234",
                "ebi": "5",
                "lbi": "5"
            }
        ],
        "client-id": "1",
        "session-state": "complete",
        "admin-state": "enabled",
        "op-type": "create",
        "op-ref-scope": "none"
    }
}

**Comment by lbertz02** [comment]
The data is part of the DPN data in the "dpns" list.

**Comment by matsusato3** [comment]
Ah, OK. Are you trying to make special DPN name which implies only one DPN that the Agent maintains?

**Comment by lbertz02** [comment]
yes, I would propose 'default'.

**Comment by lbertz02** [comment]
The alternative that we considered (and then discarded) is that we let the agent ignore the name.  Ignoring the name would be bad as an engineer could find themselves in a situation where they think they are provisioning dpn1 and dpn2 but is talking to a single DPN agent and the agent would just accept the command without error.

**Comment by lbertz02** [comment]
"Are you trying to make special DPN name which implies only one DPN that the Agent maintains?"

Exactly.  You will still have other sections of the YANG with the if-features for single and multi-dpn but this change makes CONF and CONF_BUNDLES consistent for FPC Clients regardless of single or multi-DPN agents.

**Comment by matsusato3** [comment]
After few days thinking of this issue, my conclusion is that keep as it is in the current draft. The reason is that if you want  same method for both single/multiple DPNs case, it is enough just use DPN list only. The UL/DL children under Context makes Agent, which is embedded  into a DPN,  easy not to prepare DPN list.

**Comment by lbertz02** [comment]
That is fine but it also means that we should be clear the two methods MUST not be mixed.  That is obvious in YANG and the text but requires more care when setting examples.  I'll leave the issue open for the weekly meeting tomorrow to close out.

**Comment by lbertz02** [comment]
Could you comment on this issue please?

It will add an if-feature that allows the policy structure to be passed in the CONF and CONF_BUNDLES.  It also closes out the main issue that Marco has with the current version vs. the capability we had in Version 03’s Model 1.

<<<< This comment is for issue 28# - will move

**Comment by matsusato3** [comment]
> Could you comment on this issue please?

I suppose I've answered to the issue correspondent to it.

**Comment by lbertz02** [comment]
Item closed after weekly FPC meeting on 10/27.  No action will be taken but new issue will be opened regarding Agent implementations.
