### ISSUE TITLE
Opportunity - Adding dpn to port and delete commands can allow DPN level naming scopes

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#5]
It is an opportunity and adding dpnId to a delete increases speed.  Adding dpn to a query allows stateless agents OR a way to be stateless on startup (while the operational store is sync'd).

Comments on this opportunity is appreciated.

**Comment by matsusato3** [comment]
Do you mean that Port should include not only Policies but also DPNs?

**Comment by lbertz02** [comment]
Yes.  This allows forwarding policy that impacts many Sessions to change w/o the need for us to hunt down the pointers (Contexts) to the port.   It also means ports are DPN specific as opposed to being assigned to DPNs the Contexts are assigned to.   From a speed point of view a stateless agent or multi-tenant agent will avoid large sorting to determine which DPNs are impacted.  Any time we can avoid building dual pointer lists or chasing pointers we should do so.

**Comment by lbertz02** [comment]
This has been replaced by tenant support in the latest revision.
