### ISSUE TITLE
YANG reflection of default types of Roles

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#56]
For DPN-Groups we define Data-plane-role:
    The data-plane role of the DPN-group, such as access-dpn, anchor-dpn. 

Do we want default roles of 'access-dpn' and 'anchor-dpn' added to the model?

**Comment by matsusato3** [comment]
> For DPN-Groups we define Data-plane-role:
> The data-plane role of the DPN-group, such as access-dpn, anchor-dpn.
> 
> Do we want default roles of 'access-dpn' and 'anchor-dpn' added to the model?
> 

That sounds good.
--satoru

**Comment by lbertz02** [comment]
Closed with latest commit.
