### ISSUE TITLE
Should Targets include instructions if they are Ports and Contexts?

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#7]
This would disambiguate session deletion for root Contexts as opposed to sub-bearer / tunnel connections.

**Comment by matsusato3** [comment]
This is the case of deletion that the target is a root context.  When it happens, the agent needs to resolve child contexts with the root. Is your question that the agent can do that without any helper instructions?

**Comment by lbertz02** [comment]
It is whether or not we should add more attributes for stateless agents to give them enough data to delete w/o reading the cache.  I would recommend we note this as optional in the spec if the Agent cannot query the cache in a timely manner.

**Comment by lbertz02** [comment]
Command sets are optional per latest discussion.  This will be an operator level YANG augment if they desire it.
