### ISSUE TITLE
Use of Empty to each Case?  

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/dmm-fpc-spec#8]
This can disambiguate deletion in an update for NetConf based implementations. (Over the wire JSON using JSONPatch or JSONMerge don't have this issue).

**Comment by matsusato3** [comment]
Can you explain the issue with specific example? Is there any case that the delete and remove of Netconf RPC won't work?

**Comment by lbertz02** [comment]
NetConf can do it but the RPC cannot in an update unless the update is a PUT (which the rpc update is more of a patch operation).  We need to be specific.  Will close this issue and open new one for RPC udpate.
